name: Unit Tests

on: [push]

jobs:
  unittest:
    runs-on: macos-latest
    strategy:
      max-parallel: 5
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - run: make

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - run: uv run -m unittest
